Disable ROS2 foxy in CI
r2r 0.6.5 doesn't support foxy.

```
error[E0432]: unresolved import `RCUTILS_LOG_SEVERITY`
  --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/r2r-0.6.5/src/utils.rs:63:13
   |
63 |         use RCUTILS_LOG_SEVERITY::*;
   |             ^^^^^^^^^^^^^^^^^^^^ use of undeclared type `RCUTILS_LOG_SEVERITY`

error[E0412]: cannot find type `RCUTILS_LOG_SEVERITY` in this scope
  --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/r2r-0.6.5/src/utils.rs:62:28
   |
62 |     fn to_native(&self) -> RCUTILS_LOG_SEVERITY {
   |                            ^^^^^^^^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find value `RCUTILS_LOG_SEVERITY_UNSET` in this scope
  --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/r2r-0.6.5/src/utils.rs:65:35
   |
65 |             LogSeverity::Unset => RCUTILS_LOG_SEVERITY_UNSET,
   |                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find value `RCUTILS_LOG_SEVERITY_DEBUG` in this scope
  --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/r2r-0.6.5/src/utils.rs:66:35
   |
66 |             LogSeverity::Debug => RCUTILS_LOG_SEVERITY_DEBUG,
   |                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find value `RCUTILS_LOG_SEVERITY_INFO` in this scope
  --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/r2r-0.6.5/src/utils.rs:67:34
   |
67 |             LogSeverity::Info => RCUTILS_LOG_SEVERITY_INFO,
   |                                  ^^^^^^^^^^^^^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find value `RCUTILS_LOG_SEVERITY_WARN` in this scope
  --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/r2r-0.6.5/src/utils.rs:68:34
   |
68 |             LogSeverity::Warn => RCUTILS_LOG_SEVERITY_WARN,
   |                                  ^^^^^^^^^^^^^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find value `RCUTILS_LOG_SEVERITY_ERROR` in this scope
  --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/r2r-0.6.5/src/utils.rs:69:35
   |
69 |             LogSeverity::Error => RCUTILS_LOG_SEVERITY_ERROR,
   |                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find value `RCUTILS_LOG_SEVERITY_FATAL` in this scope
  --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/r2r-0.6.5/src/utils.rs:70:35
   |
70 |             LogSeverity::Fatal => RCUTILS_LOG_SEVERITY_FATAL,
   |                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^ not found in this scope
```