[arci-urdf-viz] Add sleep to test_web.rs to wait for web server to start
Without it, a connection error occurs in CI:

```text
thread 'test_set_get_vel' panicked at 'called `Result::unwrap()` on an `Err` value: http://127.0.0.1:8888/get_joint_positions: Connection Failed: Connect error: Connection refused (os error 111)

Caused by:
    Connection refused (os error 111)', arci-urdf-viz/tests/test_web.rs:14:10
```