Fix clippy::items_after_test_module warning
```
error: items after a test module
   --> openrr-apps/src/robot_config.rs:925:1
    |
925 | mod test {
    | ^^^^^^^^
...
939 | impl RobotConfig {
    | ^^^^^^^^^^^^^^^^
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#items_after_test_module
    = note: `-D clippy::items-after-test-module` implied by `-D warnings`
    = help: to override `-D warnings` add `#[allow(clippy::items_after_test_module)]`
    = help: move the items to before the test module was defined
```